stages:
  - init
  - run

variables:
  BASE_BODY: /home/gitlab-runner/allure/$CI_PROJECT_NAME

include: 
  - project: 'devops-internal/template-cicd'
    ref: master
    file: .gitlab-ci-templates-qa.yml